<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Domain\CommonErrors.fs" />
    <Compile Include="Domain\ConstrainedType.fs" />
    <Compile Include="Domain\CommonTypes.fs" />
    <Compile Include="Domain\ExerciseSets.fs" />
    <Compile Include="Domain\UserAggregate.fs" />
    <Compile Include="Domain\ExerciseCategoryAggregate.fs" />
    <Compile Include="Domain\ExerciseDefinitionAggregate.fs" />
    <Compile Include="Domain\RoutineAggregate.fs" />
    <Compile Include="Domain\WorkoutAggregate.fs" />
    <Compile Include="Domain\DomainErrors.fs" />
    <Compile Include="Domain\DomainEvents.fs" />
    <Compile Include="Time\SystemClock.fs" />
    <Compile Include="Persistence\Abstractions.fs" />
    <Compile Include="Workflows\Abstractions.fs" />
    <Compile Include="Workflows\ErrorLoggingDecorator.fs" />
    <Compile Include="Workflows\CommonDtos.fs" />
    <Compile Include="Workflows\ExerciseCategory\CreateExerciseCategory.fs" />
    <Compile Include="Workflows\ExerciseCategory\GetAllExerciseCategories.fs" />
    <Compile Include="Workflows\ExerciseCategory\GetExerciseCategory.fs" />
    <Compile Include="Workflows\ExerciseCategory\RenameExerciseCategory.fs" />
    <Compile Include="Workflows\ExerciseCategory\DeleteExerciseCategory.fs" />
    <Compile Include="Workflows\ExerciseDefinition\CreateExerciseDefinition.fs" />
    <Compile Include="Workflows\User\CreateUser.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FsToolkit.ErrorHandling" Version="4.16.0" />
    <PackageReference Include="FsToolkit.ErrorHandling.TaskResult" Version="4.16.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Common\Common.fsproj" />
  </ItemGroup>

</Project>
