<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <Compile Include="Persistence\InternalExtensions.fs" />
    <Compile Include="Persistence\FindFluentExtensions.fs" />
    <Compile Include="Persistence\Exceptions.fs" />
    <Compile Include="Persistence\MongoSettings.fs" />
    <Compile Include="Persistence\SerializationSettings.fs" />
    <Compile Include="Persistence\MongoObjectIdProvider.fs" />
    <Compile Include="Persistence\Documents\IDocument.fs" />
    <Compile Include="Persistence\Documents\UserDocument.fs" />
    <Compile Include="Persistence\Documents\ExerciseCategoryDocument.fs" />
    <Compile Include="Persistence\Documents\ExerciseSetsDto.fs" />
    <Compile Include="Persistence\Documents\ExerciseDefinitionDocument.fs" />
    <Compile Include="Persistence\Documents\RoutineDocument.fs" />
    <Compile Include="Persistence\Documents\WorkoutDocument.fs" />
    <Compile Include="Persistence\Mapping\IDocumentMapper.fs" />
    <Compile Include="Persistence\Mapping\UserDocumentMapper.fs" />
    <Compile Include="Persistence\Mapping\ExerciseCategoryDocumentMapper.fs" />
    <Compile Include="Persistence\Mapping\ExerciseSetDtoMapper.fs" />
    <Compile Include="Persistence\Mapping\ExerciseDefinitionDocumentMapper.fs" />
    <Compile Include="Persistence\Mapping\RoutineDocumentMapper.fs" />
    <Compile Include="Persistence\MongoContext.fs" />
    <Compile Include="Persistence\Repositories\EntityRepositoryBase.fs" />
    <Compile Include="Persistence\Repositories\OwnedEntityRepositoryBase.fs" />
    <Compile Include="Persistence\Repositories\UserRepository.fs" />
    <Compile Include="Persistence\Repositories\ExerciseCategoryRepository.fs" />
    <Compile Include="Persistence\Repositories\ExerciseDefinitionRepository.fs" />
    <Compile Include="Persistence\Repositories\RoutineRepository.fs" />
    <Compile Include="InfrastructureServiceExtensions.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FSharp.Core" />
    <PackageReference Include="FsToolkit.ErrorHandling" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" />
    <PackageReference Include="MongoDB.Driver" />
    <PackageReference Include="Validus" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Common\Common.fsproj" />
    <ProjectReference Include="..\GymDiary.Application\GymDiary.Application.fsproj" />
    <ProjectReference Include="..\GymDiary.Core\GymDiary.Core.fsproj" />
    <ProjectReference Include="..\MongoDB.FSharp.Serialization\MongoDB.FSharp.Serialization.fsproj" />
  </ItemGroup>

</Project>
