<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <Compile Include="Infrastructure\InternalExtensions.fs" />
    <Compile Include="Infrastructure\FindFluentExtensions.fs" />
    <Compile Include="Infrastructure\Exceptions.fs" />
    <Compile Include="Infrastructure\MongoOptions.fs" />
    <Compile Include="Infrastructure\SerializationSettings.fs" />
    <Compile Include="Abstractions\IDocument.fs" />
    <Compile Include="Abstractions\IDocumentMapper.fs" />
    <Compile Include="Documents\UserDocument.fs" />
    <Compile Include="Documents\ExerciseCategoryDocument.fs" />
    <Compile Include="Documents\ExerciseSetsDto.fs" />
    <Compile Include="Documents\ExerciseDefinitionDocument.fs" />
    <Compile Include="Documents\RoutineDocument.fs" />
    <Compile Include="Documents\WorkoutDocument.fs" />
    <Compile Include="Mapping\UserDocumentMapper.fs" />
    <Compile Include="Mapping\ExerciseCategoryDocumentMapper.fs" />
    <Compile Include="Mapping\ExerciseSetDtoMapper.fs" />
    <Compile Include="Mapping\ExerciseDefinitionDocumentMapper.fs" />
    <Compile Include="Mapping\RoutineDocumentMapper.fs" />
    <Compile Include="MongoContext.fs" />
    <Compile Include="Repositories\Base\EntityRepositoryBase.fs" />
    <Compile Include="Repositories\Base\OwnedEntityRepositoryBase.fs" />
    <Compile Include="Repositories\UserRepository.fs" />
    <Compile Include="Repositories\ExerciseCategoryRepository.fs" />
    <Compile Include="Repositories\ExerciseDefinitionRepository.fs" />
    <Compile Include="Repositories\RoutineRepository.fs" />
    <Compile Include="PersistenceServiceExtensions.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FSharp.Core" />
    <PackageReference Include="FSharp.UMX" />
    <PackageReference Include="FsToolkit.ErrorHandling" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
    <PackageReference Include="Microsoft.Extensions.Options.DataAnnotations" />
    <PackageReference Include="MongoDB.Driver" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Common\Common.fsproj" />
    <ProjectReference Include="..\GymDiary.Application\GymDiary.Application.fsproj" />
    <ProjectReference Include="..\MongoDB.FSharp.Serialization\MongoDB.FSharp.Serialization.fsproj" />
  </ItemGroup>

</Project>
