<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="InternalExtensions.fs" />
    <Compile Include="FindFluentExtensions.fs" />
    <Compile Include="Exceptions.fs" />
    <Compile Include="Documents.fs" />
    <Compile Include="MongoSettings.fs" />
    <Compile Include="IdProvider.fs" />
    <Compile Include="Documents\UserDocument.fs" />
    <Compile Include="MongoContext.fs" />
    <Compile Include="Conversion\ExerciseCategoryDocument.fs" />
    <Compile Include="Conversion\ExerciseSetDocument.fs" />
    <Compile Include="Conversion\ExerciseDefinitionDocument.fs" />
    <Compile Include="Conversion\RoutineDocument.fs" />
    <Compile Include="Conversion\ExerciseSessionDocument.fs" />
    <Compile Include="Conversion\WorkoutSessionDocument.fs" />
    <Compile Include="Repositories\UserRepository.fs" />
    <Compile Include="Repositories\ExerciseCategoryRepository.fs" />
    <Compile Include="Repositories\ExerciseDefinitionRepository.fs" />
    <Compile Include="SerializationSettings.fs" />
    <Compile Include="PersistenceServiceCollectionExtensions.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FsToolkit.ErrorHandling.TaskResult" Version="4.16.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="8.0.1" />
    <PackageReference Include="MongoDB.Driver" Version="2.23.2" />
    <PackageReference Include="Validus" Version="4.1.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Common\Common.fsproj" />
    <ProjectReference Include="..\GymDiary.Core\GymDiary.Core.fsproj" />
    <ProjectReference Include="..\MongoDB.FSharp.Serialization\MongoDB.FSharp.Serialization.fsproj" />
  </ItemGroup>

</Project>
