<Project Sdk="Microsoft.NET.Sdk">
  
  <ItemGroup>
    <Compile Include="Primitives\ConstrainedType.fs" />
    <Compile Include="Primitives\SharedTypes.fs" />
    <Compile Include="Users\User.fs" />
    <Compile Include="Users\UserErrors.fs" />
    <Compile Include="ExerciseCategories\ExerciseCategory.fs" />
    <Compile Include="ExerciseCategories\ExerciseCategoryErrors.fs" />
    <Compile Include="ExerciseDefinitions\ExerciseSet.fs" />
    <Compile Include="ExerciseDefinitions\ExerciseDefinition.fs" />
    <Compile Include="Routines\Routine.fs" />
    <Compile Include="Workouts\Snapshots.fs" />
    <Compile Include="Workouts\Workout.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FSharp.Core" />
  </ItemGroup>

</Project>
