<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="FSharp.Core" />
    <PackageReference Include="FsToolkit.ErrorHandling" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="Time\TimeProviderExtensions.fs" />
    <Compile Include="Identity\Abstractions.fs" />
    <Compile Include="Persistence\Abstractions.fs" />
    <Compile Include="Workflows\Abstractions.fs" />
    <Compile Include="Workflows\Validation.fs" />
    <Compile Include="ExerciseCategories\CreateExerciseCategoryWorkflow.fs" />
    <Compile Include="ExerciseCategories\GetExerciseCategoryWorkflow.fs" />
    <Compile Include="ExerciseCategories\GetAllExerciseCategoriesWorkflow.fs" />
    <Compile Include="ExerciseCategories\RenameExerciseCategoryWorkflow.fs" />
    <Compile Include="ApplicationServiceExtensions.fs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GymDiary.Domain\GymDiary.Domain.fsproj" />
  </ItemGroup>

</Project>
