<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="TypeUtils.fs" />
    <Compile Include="Serializers\ListSerializer.fs" />
    <Compile Include="Serializers\OptionSerializer.fs" />
    <Compile Include="FSharpTypeConventions.fs" />
    <Compile Include="FSharpTypeSerializers.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MongoDB.Driver" />
  </ItemGroup>

</Project>
